language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t mtalele/docker-react -f Dockerfile.dev .    

script:
  - docker run mtalele/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeansstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-973541247255"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $Access\ key\ id
  secret_access_key: $Secret\ access\ key
