language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t mtalele/docker-react -f Dockerfile.dev .

script:
  - docker run mtalele/docker-react npm run test -- --coverage
