language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t mtalele/docker-react -f Dockerfile.dev .    

script:
  - docker run -e CI=true mtalele/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-docker-1"
  env: "DockerDocker1-env"
  bucket_name: "elasticbeanstalk-us-east-2-973541247255"
  bucket_path: "docker-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
